### ISSUE TITLE
ArmoredInputStream fails to detect armor CRC error

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#159]
Hi @vanitasvitae , this is actually not a bug in PGPainless, but something we have recently found in the BouncyCastle (full story here https://github.com/FlowCrypt/flowcrypt-android/issues/1347), and @tomholub asked me to ask you to deal with this. The idea we've finally got (https://github.com/FlowCrypt/flowcrypt-android/issues/1347#issuecomment-886496948) is to submit issue to BC, and also to try to fix on our own and temporarily put fixed class into PGPainless (and of course whole PGPainless should use it), until BC fixes it on their side and publish new version on the Maven Central. But since their release cycle is quite long (I have waited for v1.69 for over than half of a year) this is unlikely to happen very quickly and we need to have this fixed faster.
Here https://github.com/IvanPizhenko/bctest I have prepared a project with single unit test which demonstrates the issue.  You may provide link directly to my repo when reporting issue to BC or make a fork, up to you.

**Comment by vanitasvitae** [comment]
I see what the issue is.

When I use `int i = armorIn.read()` to read from the stream, BC fails as expected.
However, using `armorIn.read(bytes)` does not throw.

This is due to java's default implementation of `InputStream` silently swallowing IOExceptions (wtf???). See [InputStream source](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/io/InputStream.java#L286).
This is why the exception is not handed up for us to catch it.

I guess most straight forward fix on BCs side would be to override `read(bytes, offset, length)` to not swallow exceptions.

Temporarily we could fix this by creating out own `read(inputstream, bytes)` helper method and a custom implementation of `Streams.pipeAll(in, out)`.

**Comment by vanitasvitae** [comment]
I created https://github.com/bcgit/bc-java/pull/999 to fix this issue upstream.

Until the PR is merged and a new BC release is drafted, I implemented a workaround in PGPainless, which avoids using `stream.read(bytes)` and `stream.read(bytes, offset, length)` in favor of `int i = stream.read()`.

**Comment by IvanPizhenko** [comment]
Great finding! Thank you Paul!

**Comment by vanitasvitae** [comment]
I created a release containing the fix :)

**Comment by vanitasvitae** [comment]
The supplied fix is not sufficient.
As an alternative solution I'm exploring extending `ArmoredInputStream` with a wrapper class that modifies the behavior of read(bytes, offset, length).

Unfortunately, testing revealed that PGPainless' nesting of streams causes the ArmoredInputStream to be read exactly empty, such that the crc checksum verification is not called (it gets called only when byte n+1 gets read).

Fixing this is a bigger undertaking I fear. For the time being we might consider reading armored inputs into a byte array completely, before passing the unarmored representation down to the decryption code, although I find this an ugly, inefficient workaround.

**Comment by vanitasvitae** [comment]
I found a way to ensure that ArmoredInputStreams are being drained completely.

**Comment by vanitasvitae** [comment]
I created a new release which should soon be available on maven central.

**Comment by IvanPizhenko** [comment]
Sounds great. I will try it as soon as it is available.
