### ISSUE TITLE
Check for error message on symmetrically-encrypted message with certain bad password

### ISSUE THREAD

**Issue by rrrooommmaaa** [pgpainless/pgpainless#174]
I earlier filed this issue to OpenPGP.js https://github.com/openpgpjs/openpgpjs/issues/1405
They responded that session key validity check as defined in 5.7 of RFC4880 should NOT be used for password-protected messages, because of possible [decryption oracle attack](https://eprint.iacr.org/2005/033.pdf).
So we're getting "Modification detected" error in about 10 out of 256 cases of incorrect password.
Here's the message to reproduce the situation with password "wrong pwd"
```
-----BEGIN PGP MESSAGE-----
Version: FlowCrypt 7.5.9 Gmail Encryption
Comment: Seamlessly send and receive encrypted email

wcFMAzBfgamu0SA1ARAAsVO7mCvul8NuZL3FhjAtGMvKOwx74lcr6XX2n8AP
E9TxNJOGuS8HshcI2kxap3PKusS0ZT40wnHc095PdqVRSH+PJ/69DQb84GSa
VmOFH4bV/JBgiC9t+4kvNQL/epxrTajPMG0l8vNwRGbsuB70aMlvMgfHKiC5
N8bcf1p7TPnMInfcv/tQH35MnjyPi0xVjN2NOXUNQacyEHUfhSjWm049qWP/
mvoZDWdWaW4qU7CWkBSm+vl4o6k6IHiRYIKoG4OYAwhrNSNA4vhcjZc/ABI6
aCtsD8+0Ts+mcNDbIdfNnLxT1yqhv46CEfFMyDdZ2BkYJkasECkwCKRtoMBN
+RcPB28a+OQH/Sv2g/NCzmpQe9dZBWWRyVv1HbOqxE7LH2/IHolDg+GrL1ut
j1T0bKvf//1o/WHwRHfes05dD4J5l+bDVykS9gmdeAUOyQPGw+rucSyPDwXC
FbngRropLlCiGSu9L08uxquLIq80f5HUML5xM3E9M2/v9mt/SnSjcwU47zPs
5T91q9AS8eiGS4kBzmF1NGosDX3s1CC1Vw8QjcN45zcIMgXxEQl5fDAD+nLY
49+VanZtcJo5AFlBczVFhDR2HIeGyaau3Kxcxa6CsmGIFjoM2RS/FkbLqKKY
leYGJYTZKiRSTTOhSZWgwnn6Pk4hewEdqhE4PAJxHTTDLgQJAwjuV5FCYxZT
4eDKWmMYMyGgMlOZ1/zFS7RQTvA35f2JIzSqO41EgX1ga6bSwtIBspb22z2+
ngCjl3FSWWFeKDgmq8DBIe4qGsQqVTvVXR4V44xiEh651nQPY3jMmAysByYn
JxKWo6Lwew3Z+IHK7AtK+i5asqNGluRuqIY+QgdVRbdJl678Lzo2ImtPjnaN
Wbz4xmk+lJVuyTxiK8hnEVZUPiYogniQ6ZgzTiKjkDiL7OjdxVwm/ZAnoHNv
W6e994A0g3PQ6k6Lon/pd0aYkfMBpo8CXWq+0CRX9Uqux/FziZ9kAnPlS56o
XQWJISz/F5ZlbcMTjzfBX83FY/G/hTiuu0bo0sBhOYKKeo6+thmbPiGDjIuG
hTnw4avIimw1Qqavj08mq0wbfPEQ9DakTfc6IUcqVKkyceBV6k95D9g8EfYc
mSXxlHwR/KLZKE50dUfFYOHv9FtrbFYO9wkTcddT6N5Y/RxfaOqEhNQWsrFO
BlXfhezebmGzqUc/qFbnJYWoIAicP8hAs+0gOTKVNafyMuD7Q2ruh2/41h/i
Iboa0EGJ4eNNSIAvJZ6ehDnTbPLp/9YYIrBoIGLZYNXyeF7bCllwnNdV6MhC
fhsU+ekP2Dr0dk7WdCAOLmeLoPzZnTHMUeaqRFYSM2dqVt35mMO7beDrCfnW
Q2wW+lSaNMyHHs4ao7PkBIcr92VJMCCiFuQ7SOFsGSGMgOeoIWmQxbUhuqcS
RUhoEspQRhQ/Ly4AlEdYRIOvHclyi8yAVyJE3xxInIfBHxdkon3h6qS5iRyD
WrVhBuXMir9bHqqUym/N7OVmDa47cf7/DNEK0SEFRRWIQh+6KmpDk2Xe5uL+
gTzcCID3/oEcmq5t3aOKFA8PVZ9qy9EKLzSVL/mHxrzBHFamo+5Vrq/+GHC4
bTZkMSGiJ6JL4qsR/Sdzk8hmNY+7JNx72m9YO9X8wQuFzlLrQvdICngOUBlG
2wo8QyggQyOeNdGF1Ys7skolmr80WfKr7We5aOEYn+zRaTM6k3f843LJWhNG
jkZgvkrYlQAF8e5V09Yr8Vx3YF6zMJyt4c7VGIfaxv25J6xNYbH/bRGY3Stf
rUHGK+rXNCMK8uobFqq0iTOorh3BXgYsM7eN/xWQyxDS8un75M2j8p+cAsyf
HXN3SDW8JAr9xyoj5iZpBPf7+Nht9p5e3LfzjoXa6H2Ls+V8cCZiO+bmKutL
MAbht0v3nw56jNgUL8QsLtUwdCgDuNDP2IL9JO239o2t0gBOlfapvcjxMGPe
coIlduJiUw==
=CRev
-----END PGP MESSAGE-----
``` 

@vanitasvitae Please check how this is handled in this project.

**Comment by vanitasvitae** [comment]
I'm not quite sure if I understand the attack properly, so take what I say with a grain of salt.

As I understand it, the quick check (comparison of the two first bytes of the plaintext) enables an attacker to efficiently determine the first two bytes of the encrypted plaintext.

Why should this affect Password-based encryption more than it does Public-Key based encryption? The process of using the session key to decrypt the plaintext stays the same.
By that logic, the quick check should be disabled for both public key and password protected messages. I can't find a recommendation to disable the quick check only for password-based encryption in the linked paper either.

What's even more confusing is that you can find comments in Bouncycastle's source code (which I think are related to this issue), which [disable the quick check for public key encrypted messages](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/j2me/org/bouncycastle/openpgp/PGPPublicKeyEncryptedData.java#L139), but [not for password based encryption](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/pg/src/main/j2me/org/bouncycastle/openpgp/PGPPBEEncryptedData.java#L115). They even claim the opposite ("Note: the oracle attack on "quick check" bytes is not deemed a security risk for PBE") So they do the opposite of what OpenPGP.js supposedly does.

So OpenPGP.js disables the quick check for password-based encryption,
Bouncycastle for Public Key encryption, and I would assume that really you should disable it for either mechanism.

To answer your original question of whether this affects PGPainless: PGPainless is based on Bouncycastle and therefore inherits its behaviour for message decryption and it is not easily possible to change its behaviour from the outside.

PGPainless will therefore throw a MissingDecryptionMethodException stating
```
Decryption failed - No suitable decryption key or passphrase found
```

**Comment by vanitasvitae** [comment]
For the record, I created an investigative test class for this:
https://github.com/pgpainless/pgpainless/blob/989bf1a628708f338eca904e7c7492591b45e698/pgpainless-core/src/test/java/investigations/WrongPassphraseSymmetricEncryptionTest.java

**Comment by vanitasvitae** [comment]
As @teythoon pointed out:

> even if you don't look at the quickcheck, then the very next thing you need to do is parse a packet header.
> if the session key is wrong, you'll fail at that point
> mostly the same point as the quickcheck
> in fact, you can improve the quickcheck by looking at the next packet header

**Comment by rrrooommmaaa** [comment]
> PGPainless is based on Bouncycastle and therefore inherits its behaviour for message decryption and it is not easily possible to change its behaviour from the outside.

Well, I think it's not necessary to deep-dive into the internal implementation, just merge two errors ('Wrong password' and 'Bad MDC') at the top level into one ("Wrong password or message has been tampered with")

**Comment by larabr** [comment]
> As @teythoon pointed out:
> > even if you don't look at the quickcheck, then the very next thing you need to do is parse a packet header.
if the session key is wrong, you'll fail at that point

Since this is a security sensitive matter, I'd just like to point out that this is only true if you process the packets sequentially, "trusting" whatever you decrypted on the fly, and verifying the MDC only at the end. This is not the safest way to proceed.
Instead, it is possible to avoid exposing a decryption oracle altogether by first checking the MDC, and only process the decrypted packet header (and everything else) after that. This can be done (in principle) because the MDC is at a fixed/known position at the end of the decrypted data.

**Comment by vanitasvitae** [comment]
Currently in PGPainless, packets are indeed processed sequentially, so the user has to make sure to properly discard message contents as untrusted once an MDC error is being thrown on stream close.

@rrrooommmaaa, @tomholub while I suppose that sequential processing has its pro's especially in embedded or mobile environments with constraint memory, do you think it would be desirable for a server side component to also have a non-sequential implementation?
If so, I can put it on the road map.

**Comment by tomholub** [comment]
Our server side code doesn't do any handling of actual messages - it only concerns itself with key management. Therefore at the moment I don't see any way to utilize approaches that are different from how we do it now.

**Comment by vanitasvitae** [comment]
Okay, I will close this for now then.
Since we are sequentially parsing packets at the moment, parsing the message will fail anyways once we read the first (very likely invalid) packet tag, so disabling the quick check does not yield much value in our case. Even if it would be desirable for us, this change would need to be made inside of BC.

I will keep it in mind though, should we ever create a non-sequential message processor.

**Comment by teythoon** [comment]
> Since this is a security sensitive matter, I'd just like to point out that this is only true if you process the packets sequentially, "trusting" whatever you decrypted on the fly, and verifying the MDC only at the end. This is not the safest way to proceed.
Instead, it is possible to avoid exposing a decryption oracle altogether by first checking the MDC, and only process the decrypted packet header (and everything else) after that. This can be done (in principle) because the MDC is at a fixed/known position at the end of the decrypted data.

Checking the MDC (and signatures) before releasing any plaintext also has the benefit of not releasing unauthenticated plaintext to the consumer.

But, "in principle" is key here.  To do that, you either have to buffer arbitrary amounts of data, or implement a two-pass scheme where you either mask the plaintext before giving it to the consumer (who then has to buffer arbitrary amounts of data) and only release the unmasking key once the MDC checks out, or if you have the whole encrypted message in a buffer, do the decryption twice, once for verifying the MDC, second time to pass the plaintext to the consumer.

Buffering arbitrary amounts of data is not possible, and doing any kind of two-pass scheme will halve your performance, at the very least once you blow your CPU's cache.  I'd be very surprised (but would love to know!) if any implementation actually implements any of the above schemes, or any other scheme that we didn't think of.

In Sequoia, we withhold a configurable but fixed amount of data from the caller (by default 25MiB, see the [documentation](https://docs.sequoia-pgp.org/sequoia_openpgp/parse/stream/constant.DEFAULT_BUFFER_SIZE.html)), releasing it only once the MDC checks out and the consumers policy with respect to message structure and signature verifications is satisfied.

The default covers most small messages including what typical email providers accept as maximum message size.  It is configurable so that it can be adapted to other domains and computation environments.

But, let's face it, SEIP+MDC is an ad-hoc non-chunked authentication scheme that does a poor job to protect the ciphertext integrity.  The only solution is AEAD with small chunks.
