### ISSUE TITLE
a way to extract public key from private key ring

### ISSUE THREAD

**Issue by tomholub** [pgpainless/pgpainless#22]
OpenPGP.js allows me to do something like:

```js
const {keys: [prv]} = await openpgp.key.readArmored(`-----BEGIN PGP PRIVATE KEY-----`);
const pub = prv.toPublic();
console.log(pub.armor()); // -----BEGIN PGP PUBLIC KEY-----
```
It will likely just iterate over the contents, filter just the public ones, and then give me a way to armor it back as above.

It would be nice to be able to do this with similar ease.

**Comment by vanitasvitae** [comment]
I think this should be pretty straight forward, even with BC.
```java
PGPKeyRing prvAndPub = PGPainless.readKeyRing().keyRing("-----BEGIN PGP PRIVATE KEY-----");
PGPPublicKeyRing pub = prvAndPub.getPublicKeys();
ByteArrayOutputStream out = new ByteArrayOutputStream();
ArmoredOutputStream armor = new ArmoredOutputStream(out);
ByteArrayInputStream in = new ByteArrayInputStream(pub.getEncoded());
Streams.pipeAll(in, armor);
armor.close();
System.out.println(out.toString());
```

But yeah, it would be nice to have some utility methods so that the user just has to call
```java
PGPainless.toArmoredString(pgpPrivateKeyRing);
```
in order to receive `-----BEGIN PGP PRIVATE KEY-----`.

Edit: For retrieving an PGPPublicKeyRing object from a PGPPrivateKeyRing, there is already a [utility method](https://github.com/pgpainless/pgpainless/blob/master/pgpainless-core/src/main/java/org/pgpainless/key/util/KeyRingUtils.java#L28) which we might want to expose more to the user.

**Comment by tomholub** [comment]
> Edit: For retrieving an PGPPublicKeyRing object from a PGPPrivateKeyRing, there is already a utility method which we might want to expose more to the user.

Great - part of the effort here will also be comprehensive documentation of all of the available APIs.

This being Java, there may be some tool that will auto-create docs which you can then enrich, using annotations or whatnot. I've been using OpenAPI in a similar manner (for api endpoints) and happy with the results. Alternatively, manually maintaining docs is also fine.

**Comment by vanitasvitae** [comment]
Implemented as `KeyRingUtils.publicKeyRingFrom(pgpSecretKeyRing);`
