### ISSUE TITLE
implements Serializable

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#227]
Hello. I have a question. @vanitasvitae is there any reason why you don't use `Serializable` interface for data classes like [OpenPgpMetadata](https://github.com/pgpainless/pgpainless/blob/3a9473ad6c57b8abb6d1344a02fbe2aaec20f03b/pgpainless-core/src/main/java/org/pgpainless/decryption_verification/OpenPgpMetadata.java#L30-L29)?

**Comment by DenBond7** [comment]
I've looked over the whole code and have not found `Serializable` usage. So maybe you have a reason for that. Interesting to know :)

**Comment by vanitasvitae** [comment]
There is no reason. I just haven't yet had demand for that.

**Comment by DenBond7** [comment]
Ahh...that's good :). Why am I asking? On the Android side, we have a `Parcelable` interface (an optimized version of `Serializable`). We use it very often. Currently, I create a wrapper around all data from `PGPainless`. Because there is no `Serializable`. It's not productive :) It would be nice to have `Serializable` on the `PGPainless` side.

**Comment by vanitasvitae** [comment]
In that case I will start inheriting Serializable in places where it makes sense :)

**Comment by vanitasvitae** [comment]
I have never really worked with `Serializable`. Is it enough to `implements Serializable` or do I have to add [method implementations](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html) for
```
 private void writeObject(java.io.ObjectOutputStream out)
     throws IOException;
 private void readObject(java.io.ObjectInputStream in)
     throws IOException, ClassNotFoundException;
 private void readObjectNoData()
     throws ObjectStreamException;
```

Also, would I need to implement `Serializable` in classes that are fields of serializable classes too?

**Comment by DenBond7** [comment]
> Is it enough to implements Serializable

Yes, it's enough. 

> Also, would I need to implement Serializable in classes that are fields of serializable classes too?

All inner objects should implement `Serializable` or should be marked as `transient` to be skipped

I've checked some classes and found that they have `bouncycastle` objects that don't implement `Serializable`. Need to think about that.

I propose to do the following. We can leave it for later. For now, it's not a very urgent issue. I think I can work in this direction myself and post PR. I'm going to add `Serializable` to some classes one by one where it is really needed.

**Comment by wiktor-k** [comment]
I'd warn against blindly implementing `Serualizable` everywhere. This basically makes all class members (even private) part of the API contract. This may be alarming in itself but consider that the mechanism is designed to allow serializing objects with one version of your library and then deserializing them with another and this complexity can easily get out of hand.

I'd recommend first reading [Effective Java](https://www.oreilly.com/library/view/effective-java/9780134686097/) book by Joshua Bloch, there's entire section devoted to serialization (start with "Item 85: Prefer alternatives to Java serialization").

For the record there may be a relevant use case behind wanting to serialize objects but I'd inquire about this first so that we don't fall into the [XY problem](https://en.wikipedia.org/wiki/XY_problem) trap.

**Comment by vanitasvitae** [comment]
I'm closing this as stale. Feel free to re-open if you feel like this should be revisited though :)
