### ISSUE TITLE
Rework key generation API for elliptic curve keys

### ISSUE THREAD

**Issue by vanitasvitae** [pgpainless/pgpainless#33]
As not all curves can be used with all algorithms it would make sense to guide the user through the creation by first letting them chose an algorithm (eg. EdDSA) and then let them chose from a limited list of curves that are suitable for that algorithm.
It should also somehow be communicated to the user, what keys can later be used for signing and which for encryption.

Maybe it makes sense to split the KeySpec interface into EncryptionKeySpec and SignatureKeySpec interface, so that for example RSA can implement both interfaces, while ECDH and XDH implement only the EncryptionKeySpec interface and EDDSA, ECDSA implement only SignatureKeySpec.

**Comment by tomholub** [comment]
Agree it's good to guide the user in the right direction when there are combinations that make sense and combinations that don't.

I'm not entirely sure if this addresses the concern but one way to resolve this is let the user choose from a limited set of combinations that make sense instead of giving them too much flexibility. For example, in Java, if I want to derive using PBKDF2 I'll have to choose option called `PBKDF2WithHmacSHA256` and not "PBKDF2", "HMAC" and "SHA256" separately.

**Comment by vanitasvitae** [comment]
There are now different curve enum types for the different algorithms.
