### ISSUE TITLE
pgpainless build requires Android api level 9 which is quite outdated

### ISSUE THREAD

**Issue by IvanPizhenko** [pgpainless/pgpainless#66]
pgpainless build wants Android api level 9.
sdkmanager for the freshly installed Android SDK offers minimum api level 10.
Google will require soon *all* apps to target api level 30 - [read here](https://developer.android.com/distribute/best-practices/develop/target-sdk)
Isn't it time to bump it up to at least level 10? Does anyone really uses that level 9?

**Comment by vanitasvitae** [comment]
> Google will require soon all apps to target api level 30

Note that this is about newly submitted apps only. Already available apps can still target lower levels.

> sdkmanager for the freshly installed Android SDK offers minimum api level 10.

That might be a valid motivation to bump to API level 10. I will think about it.

As long as there isn't a good reason (like an important feature that we can't get without raising the minimum API level), I'd like to stay as low as possible for compatibility reasons.

As a site note: I'm not convinced to raise API levels just because of Google policies. Their plans to require devs to [surrender control of their signing keys](https://commonsware.com/blog/2020/09/23/uncomfortable-questions-app-signing.html) for example is very worrying and something I won't support.

**Comment by IvanPizhenko** [comment]
Yes, I understand you, but the fact that API level 9 is no longer available via standard SDK tools is obviously a good reason to bump it up to the oldest available version.

**Comment by IvanPizhenko** [comment]
I can even post a PR.
