### ISSUE TITLE
GenerateKeyTest. Print a private key instead of a public key

### ISSUE THREAD

**Issue by DenBond7** [pgpainless/pgpainless#95]
Hello. It seems you print a private key instead of a public key.

```
ByteArrayOutputStream bytes = new ByteArrayOutputStream();
ArmoredOutputStream armor = ArmoredOutputStreamFactory.get(bytes);
```
**secretKeys.encode(armor);**
```
armor.close();
String publicKey = new String(bytes.toByteArray());
```

https://github.com/pgpainless/pgpainless/blob/7bd12fe5d423b8bf4c7d5388870bd06a14829b99/pgpainless-core/src/test/java/org/pgpainless/key/generation/GenerateKeyTest.java#L51

**Comment by vanitasvitae** [comment]
You're right. Thanks for the notice :)

**Comment by tomholub** [comment]
This sounds like a potential vulnerability? Definitely worth writing a test for as well to ensure no regression.

**Comment by DenBond7** [comment]
> This sounds like a potential vulnerability? Definitely worth writing a test for as well to ensure no regression.

I think it's just a 'copy-paste' error.

**Comment by tomholub** [comment]
From the coding perspective, yes. From the perspective of the expectations, if user expects a public key, and it's in fact a private key, they may share it externally thinking it's public when in fact it's private. Maybe the types would not allow that so easily, but still, that would be considered a vulnerability regardless of how the bug was introduced.

**Comment by vanitasvitae** [comment]
The error has been fixed.
